<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.praktikum</groupId>
    <artifactId>stellar-burgers-autotests</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Stellar Burgers UI Tests</name>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Путь для Allure -->
        <allure.results.directory>${project.build.directory}/allure-results</allure.results.directory>
        <allure.report.directory>${project.build.directory}/site/allure-report</allure.report.directory>

        <!-- Плагин для компиляции Java -->
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>

        <!-- Версия JUnit 4 -->
        <junit.version>4.13.2</junit.version>

        <!-- Версия Jackson -->
        <jackson.version>2.13.0</jackson.version>

        <!-- Версия JavaFaker -->
        <javafaker.version>1.0.2</javafaker.version>

        <!-- WebDriverManager version -->
        <webdrivermanager.version>5.6.2</webdrivermanager.version>

        <!-- Selenium version -->
        <selenium.version>4.13.0</selenium.version>
    </properties>

    <dependencies>
        <!-- Selenium -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-devtools-v135</artifactId>
            <version>4.33.0</version>
        </dependency>

        <!-- JUnit 4 -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- WebDriverManager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>

        <!-- Allure -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit4</artifactId>
            <version>2.23.0</version>
        </dependency>

        <!-- SLF4J Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.32</version>
        </dependency>

        <!-- Jackson Databind (для сериализации/десериализации JSON) -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- JavaFaker (для генерации случайных данных) -->
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>${javafaker.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.2.0</version> <!-- используйте актуальную версию -->
        </dependency>


    </dependencies>

    <!-- Настройки сборки -->
    <build>
        <plugins>
            <!-- Плагин для компиляции и тестирования Java -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>

            <!-- Плагин для Allure Report -->
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-junit4</artifactId>
                <version>2.23.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>serve</goal>
                        </goals>
                    </execution>
                </executions>

            </plugin>

            <!-- Плагин для сборки JAR файла -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.stellarburgers.Main</mainClass> <!-- Укажи основной класс, если нужно -->
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
